"""
Command-line interface for injecting OCR-based text into PDFs.
"""

import sys
import os
import argparse
from .injector import inject_text_to_pdf


def main():
    """Main CLI entry point for pdf-inject command."""

    parser = argparse.ArgumentParser(
        description='Create searchable PDFs using spaCy Layout OCR',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # Create searchable PDF using OCR
  pdf-inject scan.pdf searchable.pdf

Note: This tool uses spaCy Layout to OCR the PDF and inject invisible text
at exact word positions for accurate search highlighting. The markdown files
generated by pdf-extract are for human readability only.

Requirements:
  pip install -e '.[local]'
  python -m spacy download en_core_web_sm
        '''
    )

    parser.add_argument('input_pdf', help='Input PDF file (scanned, no text layer)')
    parser.add_argument('output_pdf', help='Output PDF file (with searchable text)')

    args = parser.parse_args()

    if not os.path.exists(args.input_pdf):
        print(f"Error: Input PDF not found: {args.input_pdf}", file=sys.stderr)
        sys.exit(1)

    print(f"Processing: {args.input_pdf}")
    print(f"Using spaCy Layout OCR for word positioning...")

    try:
        total_pages = inject_text_to_pdf(
            args.input_pdf,
            args.output_pdf
        )
        print(f"\n✓ Searchable PDF created: {args.output_pdf}")
        print(f"  Total pages: {total_pages}")
    except Exception as e:
        print(f"\n✗ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
